## Pandas: Tabular Data
Pandas is an extremely useful library in python for structured data ,the library uses two key data structures, namely Series
and DataFrame,used to load,organize,clean,filter data efficiently

In [1]:
import pandas as pd

## first we should download the dataset and know its shape,#col,#rows and summary about it

In [2]:
df=pd.read_csv("train_and_test2.csv")

In [ ]:
df.shape #(Number of rows and columns)

(1309, 28)

In [ ]:
df.head() #show the first 5 rows

,Passengerid,Age,Fare,Sex,sibsp,zero,zero.1,zero.2,zero.3,zero.4,...,zero.12,zero.13,zero.14,Pclass,zero.15,zero.16,Embarked,zero.17,zero.18,2urvived
0,1,22.0,7.2500,0,1,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1,2,38.0,71.2833,1,1,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,1
2,3,26.0,7.9250,1,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,1
3,4,35.0,53.1000,1,1,0,0,0,0,0,...,0,0,0,1,0,0,2.0,0,0,1
4,5,35.0,8.0500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0

In [ ]:
df.info() # column names, non-null counts, dtypes

<class 'pandas.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 28 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Passengerid  1309 non-null   int64
 1   Age          1309 non-null   float64
 2   Fare         1309 non-null   float64
 3   Sex          1309 non-null   int64
 4   sibsp        1309 non-null   int64
 5   zero         1309 non-null   int64
 6   zero.1       1309 non-null   int64
 7   zero.2       1309 non-null   int64
 8   zero.3       1309 non-null   int64
 9   zero.4       1309 non-null   int64
 10  zero.5       1309 non-null   int64
 11  zero.6       1309 non-null   int64
 12  Parch        1309 non-null   int64
 13  zero.7       1309 non-null   int64
 14  zero.8       1309 non-null   int64
 15  zero.9       1309 non-null   int64
 16  zero.10      1309 non-null   int64
 17  zero.11      1309 non-null   int64
 18  zero.12      1309 non-null   int64
 19  zero.13      1309 non-null   int64
 20  zero.14      1309 non-null   int64
 21  Pclass       1309 non-null   int64
 22  zero.15      1309 non-null   int64
 23  zero.16      1309 non-null   int64
 24  Embarked     1307 non-null   float64
 25  zero.17      1309 non-null   int64
 26  zero.18      1309 non-null   int64
 27  2urvived     1309 non-null   int64
dtypes: float64(3), int64(25)
memory usage: 286.5 KB

In [ ]:
df.describe() # summary statistics for numeric columns as (count,mean,min,...)

,Passengerid,Age,Fare,Sex,sibsp,zero,zero.1,zero.2,zero.3,zero.4,...,zero.12,zero.13,zero.14,Pclass,zero.15,zero.16,Embarked,zero.17,zero.18,2urvived
count,1309.000000,1309.000000,1309.000000,1309.000000,1309.000000,1309.0,1309.0,1309.0,1309.0,1309.0,...,1309.0,1309.0,1309.0,1309.000000,1309.0,1309.0,1307.000000,1309.0,1309.0,1309.000000
mean,655.000000,29.503186,33.281086,0.355997,0.498854,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,2.294882,0.0,0.0,1.492731,0.0,0.0,0.261268
std,378.020061,12.905241,51.741500,0.478997,1.041658,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.837836,0.0,0.0,0.814626,0.0,0.0,0.439494
min,1.000000,0.170000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.000000,0.0,0.0,0.000000,0.0,0.0,0.000000
25%,328.000000,22.000000,7.895800,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,2.000000,0.0,0.0,1.000000,0.0,0.0,0.000000
50%,655.000000,28.000000,14.454200,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,3.000000,0.0,0.0,2.000000,0.0,0.0,0.000000
75%,982.000000,35.000000,31.275000,1.000000,1.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,3.000000,0.0,0.0,2.000000,0.0,0.0,1.000000
max,1309.000000,80.000000,512.329200,1.000000,8.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,3.000000,0.0,0.0,2.000000,0.0,0.0,1.000000

## Selecting and Filtering

In [ ]:
df["Passengerid"] #select col by its name

0          1
1          2
2          3
3          4
4          5
        ...
1304    1305
1305    1306
1306    1307
1307    1308
1308    1309
Name: Passengerid, Length: 1309, dtype: int64

In [ ]:
df[["Passengerid","Age"]] #select multiple col by name

      Passengerid   Age
0               1  22.0
1               2  38.0
2               3  26.0
3               4  35.0
4               5  35.0
...           ...   ...
1304         1305  28.0
1305         1306  39.0
1306         1307  38.5
1307         1308  28.0
1308         1309  28.0

[1309 rows x 2 columns]

In [ ]:
df [df["Age"]>40] #select col by condition

,Passengerid,Age,Fare,Sex,sibsp,zero,zero.1,zero.2,zero.3,zero.4,...,zero.12,zero.13,zero.14,Pclass,zero.15,zero.16,Embarked,zero.17,zero.18,2urvived
6,7,54.0,51.8625,0,0,0,0,0,0,0,...,0,0,0,1,0,0,2.0,0,0,0
11,12,58.0,26.5500,1,0,0,0,0,0,0,...,0,0,0,1,0,0,2.0,0,0,1
15,16,55.0,16.0000,1,0,0,0,0,0,0,...,0,0,0,2,0,0,2.0,0,0,1
33,34,66.0,10.5000,0,0,0,0,0,0,0,...,0,0,0,2,0,0,2.0,0,0,0
35,36,42.0,52.0000,0,1,0,0,0,0,0,...,0,0,0,1,0,0,2.0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1282,1283,51.0,39.4000,1,0,0,0,0,0,0,...,0,0,0,1,0,0,2.0,0,0,0
1284,1285,47.0,10.5000,0,0,0,0,0,0,0,...,0,0,0,2,0,0,2.0,0,0,0
1288,1289,48.0,79.2000,1,1,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,0
1295,1296,43.0,27.7208,0,1,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,0
1298,1299,50.0,211.5000,0,1,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,0

## df.loc[row_condition, column_name]

In [ ]:
df.loc[df["Age"]>30,"Passengerid"] #select passengerid column for rows where age greater than 30

1          2
3          4
4          5
6          7
11        12
        ...
1295    1296
1298    1299
1302    1303
1305    1306
1306    1307
Name: Passengerid, Length: 437, dtype: int64

## Cleaning Data
remove duplicates value,wrong data types or missing values

In [ ]:
df.isnull().sum() #number of null values

Passengerid    0
Age            0
Fare           0
Sex            0
sibsp          0
zero           0
zero.1         0
zero.2         0
zero.3         0
zero.4         0
zero.5         0
zero.6         0
Parch          0
zero.7         0
zero.8         0
zero.9         0
zero.10        0
zero.11        0
zero.12        0
zero.13        0
zero.14        0
Pclass         0
zero.15        0
zero.16        0
Embarked       2
zero.17        0
zero.18        0
2urvived       0
dtype: int64

In [ ]:
df["Age"].fillna(df["Age"].mean(),inplace=True)  #fill null values with mean of age

C:\Users\Ayman\AppData\Local\Temp\ipykernel_13380\2595122914.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["Age"].fillna(df["Age"].mean(),inplace=True)

0       22.0
1       38.0
2       26.0
3       35.0
4       35.0
        ...
1304    28.0
1305    39.0
1306    38.5
1307    28.0
1308    28.0
Name: Age, Length: 1309, dtype: float64

In [ ]:
df.dropna(inplace=True) #drop rows with missing value

In [ ]:
df.drop_duplicates(inplace=True) #remove duplicates from the dataset

## Grouping and Aggregation
Groups data by a column and computes statistics for each group

In [22]:
df.groupby("Passengerid") ["Age"].mean()

Passengerid
1       22.0
2       38.0
3       26.0
4       35.0
5       35.0
        ...
1305    28.0
1306    39.0
1307    38.5
1308    28.0
1309    28.0
Name: Age, Length: 1307, dtype: float64

In [23]:
df.groupby("Passengerid").agg({"Age":"mean","Fare":"max"})

              Age      Fare
Passengerid
1            22.0    7.2500
2            38.0   71.2833
3            26.0    7.9250
4            35.0   53.1000
5            35.0    8.0500
...           ...       ...
1305         28.0    8.0500
1306         39.0  108.9000
1307         38.5    7.2500
1308         28.0    8.0500
1309         28.0   22.3583

[1307 rows x 2 columns]

## Hands-On Lab
Step 1: Load a provided CSV dataset into a DataFrame and report its shape, columns, and dtypes.

In [36]:
df1=pd.read_csv("train.csv")
print(df1.shape)
print(df1.info())

(891, 12)
<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB
None

## Step 2: Count missing values per column and handle them (fill or drop) with a documented justification.

In [ ]:
print(df1.isnull().sum()) # count missing values
df1["Age"]=df1["Age"].fillna(df1["Age"].mean()) #fill missing values
df1["Cabin"]
df1.dropna(inplace=True) #drop rows with missing values
print(df1.isnull().sum()) #check

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64
PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

## Justification
counted missing values using (df1.isnull().sum())
filled missing values in Age with mean
drop rows with missing values using df1.dropna(inplace=True)

## Step 3: Filter the data to a meaningful subset (e.g. rows above a threshold) and describe what you find.

In [41]:
filter=df1[df1["Age"]>28]
print(filter.head())

    PassengerId  Survived  Pclass  \
1             2         1       1
3             4         1       1
4             5         0       3
6             7         0       1
11           12         1       1

                                                 Name     Sex   Age  SibSp  \
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                            Allen, Mr. William Henry    male  35.0      0
6                             McCarthy, Mr. Timothy J    male  54.0      0
11                           Bonnell, Miss. Elizabeth  female  58.0      0

    Parch    Ticket     Fare Cabin Embarked
1       0  PC 17599  71.2833   C85        C
3       0    113803  53.1000  C123        S
4       0    373450   8.0500   NaN        S
6       0     17463  51.8625   E46        S
11      0    113783  26.5500  C103        S

## Description
filterd the dataset to have only rows where Age is greater than 28,the filterd datasets contaions 5 rows,this helps in analyze their characteristics.

## Step 4: Use groupby to compute an aggregate statistic per category and interpret the result in a Markdown cell.

In [44]:
df1.groupby("Survived") ["Age"].mean()

Survived
0    30.626179
1    28.343690
Name: Age, dtype: float64

## Interpretation
Average Age of the individuals in both categories of Survival as obtained by applying groupby function the result
provides the mean of ages of individuals who  survive (Survived=1) and those who didn't survive (Survived=0)